title: Vietnam OpenStack Day
description: > # this means to ignore newlines until "baseurl:"
  The 1st OpenStack Day @ Vietnam, by Vietnam OpenStack User Group
baseurl: "/openstackday-demo/" # the subpath of your site, e.g. /blog
url: "https://hieulq.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: VietOpenStack Group
  link: "https://www.facebook.com/groups/vietstack/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/vietstack/
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty
